name = "short-url-worker"
main = "src/index.ts"
compatibility_date = "2024-02-08"

# KV Namespace Bindings
# To generate this ID, run: npx wrangler kv namespace create SHORT_URLS
[[kv_namespaces]]
binding = "SHORT_URLS"
id = "69c7cf8a99a54eadb89c230c8f4b5a06"
